### ISSUE TITLE
Script text flows into edge of screen in main assignment view

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/bernie-messenger-android#16]
![screenshot may 18 2016 2-04-45 pm](https://cloud.githubusercontent.com/assets/6752382/15369845/669e04e0-1d02-11e6-961d-03896162f14f.png)

**Comment by ajwhite** [comment]
Hrmm.. Specifically set this to [ellipsis after 2 lines](https://github.com/Bernie-2016/bernie-messenger-android/blob/develop/app/components/assignment/rows/row.js#L28).

Likely a simple solution by adding some flex/align properties on it to make sure it respects the boundaries of the container. Should be quick & ez
